
name: Run scraper daily

on:
  schedule:
    - cron: '0 5 * * *'   # svaki dan u 05:00 UTC (~07:00 lokalno)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install libraries
        run: pip install requests beautifulsoup4 pandas openpyxl

      - name: Run script
        run: python script.py

      - name: Commit changes
        run: |
          git config --global user.name 'bot'
          git config --global user.email 'bot@example.com'
          git add data.xlsx
          git commit -m "update data" || echo "no changes"
          git pull --rebase
          git push
